#!/bin/bash

if [ $1 ];
then
	mkdir $1
	cd $1
fi

echo Initializing node project...
npm init -y
echo Installing GTS...
npm i gts --save-dev
echo Initializing GTS project...
npx gts init

echo Installing cors...
npm i cors
echo Installing dotenv...
npm i dotenv --save-dev
echo Installing express...
npm i express
echo Installing express-async-errors...
npm i express-async-errors
echo Installing http-status-codes...
npm i http-status-codes
echo Installing jsonwebtoken...
npm i jsonwebtoken
echo Installing mongodb...
npm i mongodb
echo Installing zod...
npm i zod
echo Installing @types/cors...
npm i @types/cors --save-dev
echo Installing @types/express...
npm i @types/express --save-dev
echo Installing @types/jest...
npm i @types/jest --save-dev
echo Installing @types/jsonwebtoken...
npm i @types/jsonwebtoken --save-dev
echo Installing @types/node...
npm i @types/node --save-dev
echo Installing ts-node-dev...
npm i ts-node-dev --save-dev
echo Installing @types/jsonwebtoken...
npm i @types/jsonwebtoken --save-dev
